apiVersion: v1
kind: Namespace
metadata:
  name: openshift4-collectl
  labels:
    app: openshift4-collectl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift4-collectl
  namespace: openshift4-collectl
  labels:
    app: openshift4-collectl
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: openshift4-collectl
  namespace: openshift4-collectl
  labels:
    app: openshift4-collectl
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
fsGroup:
  type: RunAsAny
users:
  - system:serviceaccount:openshift4-collectl:openshift4-collectl
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
